-- =============================================================================
-- Clinical Document Intelligence Plugin — Teardown
-- =============================================================================
-- Drops ALL objects created by the plugin. Use with caution — this is irreversible.
--
-- Usage:
--   SET V_DB = 'YOUR_DATABASE';
--   SET V_SCHEMA = 'YOUR_SCHEMA';
--   Then execute this script.
--
-- Or if deploying via CoCo, read database/schema from .deployment/manifest.json.
-- =============================================================================

SET V_DB = 'REPLACE_WITH_YOUR_DATABASE';
SET V_SCHEMA = 'REPLACE_WITH_YOUR_SCHEMA';

-- Suspend tasks first (required before DROP)
EXECUTE IMMEDIATE 'ALTER TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_PIPELINE_ROOT SUSPEND';
EXECUTE IMMEDIATE 'ALTER TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_CLASSIFY_TASK SUSPEND';
EXECUTE IMMEDIATE 'ALTER TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_EXTRACT_TASK SUSPEND';
EXECUTE IMMEDIATE 'ALTER TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_PARSE_TASK SUSPEND';
EXECUTE IMMEDIATE 'ALTER TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_REFRESH_TASK SUSPEND';
EXECUTE IMMEDIATE 'ALTER TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.REFRESH_RAW_CONTENT_TASK SUSPEND';

-- Drop tasks (DAG)
EXECUTE IMMEDIATE 'DROP TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_REFRESH_TASK';
EXECUTE IMMEDIATE 'DROP TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_PARSE_TASK';
EXECUTE IMMEDIATE 'DROP TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_EXTRACT_TASK';
EXECUTE IMMEDIATE 'DROP TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_CLASSIFY_TASK';
EXECUTE IMMEDIATE 'DROP TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_PIPELINE_ROOT';
EXECUTE IMMEDIATE 'DROP TASK IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.REFRESH_RAW_CONTENT_TASK';

-- Drop streams
EXECUTE IMMEDIATE 'DROP STREAM IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_DIRECTORY_STREAM';
EXECUTE IMMEDIATE 'DROP STREAM IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.DOCS_PARSE_OUTPUT_STREAM';

-- Drop Cortex Search Services
EXECUTE IMMEDIATE 'DROP CORTEX SEARCH SERVICE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_SEARCH_SERVICE';
EXECUTE IMMEDIATE 'DROP CORTEX SEARCH SERVICE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_MODEL_SEARCH_SVC';
EXECUTE IMMEDIATE 'DROP CORTEX SEARCH SERVICE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_SPECS_SEARCH_SVC';

-- Drop Cortex Agent
EXECUTE IMMEDIATE 'DROP CORTEX AGENT IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCUMENTS_AGENT';

-- Drop Semantic View
EXECUTE IMMEDIATE 'DROP SEMANTIC VIEW IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_SEMANTIC_VIEW';

-- Drop Stored Procedures
EXECUTE IMMEDIATE 'DROP PROCEDURE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.PREPROCESS_CLINICAL_DOCS()';
EXECUTE IMMEDIATE 'DROP PROCEDURE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.EXTRACT_DOCUMENT_CLASSIFICATION_METADATA()';
EXECUTE IMMEDIATE 'DROP PROCEDURE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLASSIFY_AGGREGATED_DOCUMENTS()';
EXECUTE IMMEDIATE 'DROP PROCEDURE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.EXTRACT_DOCUMENT_TYPE_SPECIFIC_VALUES()';
EXECUTE IMMEDIATE 'DROP PROCEDURE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.EXTRACT_DOCUMENT_TYPE_SPECIFIC_VALUES_WITH_AI_AGG()';
EXECUTE IMMEDIATE 'DROP PROCEDURE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCUMENTS_PARSE_WITH_IMAGES_V2()';
EXECUTE IMMEDIATE 'DROP PROCEDURE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.GENERATE_DYNAMIC_OBJECTS()';

-- Drop UDFs
EXECUTE IMMEDIATE 'DROP FUNCTION IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.BUILD_DOCUMENT_CLASIFICATION_EXTRACTION_JSON()';
EXECUTE IMMEDIATE 'DROP FUNCTION IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.BUILD_DOC_TYPE_EXTRACTION_JSON(VARCHAR)';
EXECUTE IMMEDIATE 'DROP FUNCTION IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.INJECT_IMAGE_DESCRIPTIONS(VARCHAR, ARRAY)';

-- Drop CKE reference tables
EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_MODEL_REFERENCE';
EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_SPECS_REFERENCE';

-- Drop pipeline tables
EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCUMENTS_RAW_CONTENT';
EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.DOC_TYPE_SPECIFIC_VALUES_EXTRACT_OUTPUT';
EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.DOC_CLASSIFICATION_METADATA_ROWS';
EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.DOCS_PARSE_OUTPUT';
EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.DOCUMENT_HIERARCHY';
EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.DOCUMENT_CLASSIFICATION_EXTRACTION_FIELD_CONFIG';
EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.DOC_TYPE_SPECIFIC_EXTRACTION_CONFIG';
EXECUTE IMMEDIATE 'DROP TABLE IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_EXTRACTION_CONFIG';

-- Drop Streamlit app
EXECUTE IMMEDIATE 'DROP STREAMLIT IF EXISTS ' || $V_DB || '.' || $V_SCHEMA || '.CLINICAL_DOCS_VIEWER';

SELECT 'Teardown complete. All Clinical Document Intelligence objects removed from ' || $V_DB || '.' || $V_SCHEMA AS STATUS;
